export type PerfilExportacao =
  | "planilha"
  | "interpretacao-cega"
  | "campo-cego"
  | "voo-cego"
  | "matriz-treino";

export const PERFIS_EXPORTACAO: Record<PerfilExportacao, { descricao: string; colunasPermitidas: string[] }> = {
  planilha: {
    descricao: "Planilha para o pesquisador e dissertação",
    colunasPermitidas: [
      "Ponto_ID",
      "Codigo",
      "Latitude",
      "Longitude",
      "Latitude_DMS",
      "Longitude_DMS",
      "Municipio",
      "Municipio_Origem",
      "Codigo_IBGE",
      "Codigo_IBGE_Origem",
      "Bacia_Hidrografica",
      "Bacia_Hidrografica_Origem",
      "Bloco_Espacial",
      "Estrato_ID",
      "Elevacao_m",
      "Elevacao_m_Origem",
      "Declividade_pct",
      "Declividade_pct_Origem",
      "Declividade_graus",
      "Declividade_graus_Origem",
      "Curvatura_Perfil",
      "Curvatura_Perfil_Origem",
      "Curvatura_Plana",
      "Curvatura_Plana_Origem",
      "Acumulo_Fluxo",
      "Acumulo_Fluxo_Origem",
      "TWI",
      "TWI_Origem",
      "Ordem_Solo",
      "Ordem_Solo_Origem",
      "Subordem_Solo",
      "Subordem_Solo_Origem",
      "Grande_Grupo_Solo",
      "Grande_Grupo_Solo_Origem",
      "Tipo_Unidade_Solo",
      "Tipo_Unidade_Solo_Origem",
      "Confianca_Pedologica",
      "Erodibilidade_Classe",
      "Erodibilidade_Classe_Origem",
      "Frequencia_Solo_Nu",
      "Frequencia_Solo_Nu_Origem",
      "Precip_Acum_30d_mm",
      "Precip_Acum_30d_mm_Origem",
      "Precip_Acum_90d_mm",
      "Precip_Acum_90d_mm_Origem",
      "I30_Max_mm_h",
      "I30_Max_mm_h_Origem",
      "N_Eventos_Erosivos",
      "N_Eventos_Erosivos_Origem",
      "Indice_Mecanismo",
      "Indice_Mecanismo_Origem",
      "Rotulo_Classe",
      "Rotulo_Modalidade",
      "Rotulo_Observador",
      "Rotulo_Observado_Em",
      "Rotulo_Confianca",
      "Rotulo_Kappa",
      "Rotulo_Divergencia",
      "CAR_Codigo",
      "CAR_Status",
      "Titular_Mascarado",
      "Documento_Mascarado",
      "Area_Imovel_ha",
      "RUSLE_Fator_R",
      "RUSLE_Fator_R_Origem",
      "RUSLE_Fator_K",
      "RUSLE_Fator_K_Origem",
      "RUSLE_Fator_LS",
      "RUSLE_Fator_LS_Origem",
      "RUSLE_Fator_C",
      "RUSLE_Fator_C_Origem",
      "RUSLE_Fator_P",
      "RUSLE_Fator_P_Origem",
      "RUSLE_Perda_Solo_t_ha_ano",
      "RUSLE_Perda_Solo_t_ha_ano_Origem",
      "RUSLE_Memoria_Calculo",
      "Campos_Estimados",
      "Rastreio_Versao_Motor",
      "Rastreio_Cenas",
      "Rastreio_Calculado_Em",
    ],
  },
  "interpretacao-cega": {
    descricao: "Plano cego para intérpretes da Fase A",
    colunasPermitidas: [
      "Codigo",
      "Latitude",
      "Longitude",
      "Janela_Inicio",
      "Janela_Fim",
      "Referencia_Cena_Tile",
    ],
  },
  "campo-cego": {
    descricao: "Plano cego para equipe de campo da Fase B",
    colunasPermitidas: [
      "Codigo",
      "Latitude",
      "Longitude",
      "Latitude_DMS",
      "Longitude_DMS",
      "Municipio",
      "Status_Fundiario",
      "Motivo_Acesso",
      "Codigo_CAR",
      "Titular_Mascarado",
      "Rota_Acesso",
    ],
  },
  "voo-cego": {
    descricao: "Plano cego para intérprete de ortomosaico de drone (Fase D)",
    colunasPermitidas: [
      "Codigo",
      "Latitude",
      "Longitude",
      "Area_Voo_Poligono",
    ],
  },
  "matriz-treino": {
    descricao: "Matriz final para modelagem supervisionada externa (PPGTCA 2026)",
    colunasPermitidas: [
      "Ponto_ID",
      "Bloco_Espacial",
      "Elevacao_m",
      "Declividade_pct",
      "Declividade_graus",
      "Curvatura_Perfil",
      "Curvatura_Plana",
      "Acumulo_Fluxo",
      "TWI",
      "Ordem_Solo",
      "Subordem_Solo",
      "Grande_Grupo_Solo",
      "Erodibilidade_Classe",
      "Frequencia_Solo_Nu",
      "Banda_B2",
      "Banda_B4",
      "Banda_B8",
      "Banda_B12",
      "NDVI",
      "BSI",
      "RUSLE_Fator_K",
      "RUSLE_Fator_R",
      "RUSLE_Perda_Solo",
      "Precip_Acum_30d_mm",
      "Precip_Acum_90d_mm",
      "I30_Max_mm_h",
      "N_Eventos_Erosivos",
      "Indice_Mecanismo",
      "Classe_Alvo_Binaria",
      "Rotulo_Classe",
      "Rotulo_Modalidade",
    ],
  },
};

export function obterColunasPermitidas(perfil: PerfilExportacao): string[] {
  return PERFIS_EXPORTACAO[perfil].colunasPermitidas;
}
